openapi: "3.0.0"

#https://swagger.io/docs/specification/basic-structure/
info:
    version: "1.0.0"
    title: "POC for API Documentation"
    description:  "POC for API Doc Design and Collaboration"

#https://swagger.io/docs/specification/api-host-and-base-path/
servers:
    - url: http://localhost:5673

# https://swagger.io/docs/specification/grouping-operations-with-tags/
tags:
  - name: Charts
  - name: Examples

#https://swagger.io/docs/specification/paths-and-operations/
paths:
    /meta/charts:
        $ref: "./paths/charts/charts.yaml"
    /meta/charts/{chartId}/edition:
        $ref: "./paths/charts/chart.yaml"
    /api/emaples:
        $ref: "./paths/examples/examples.yaml"
    /api/emaples/{exampleId}:
        $ref: "./paths/examples/example.yaml"
# https://swagger.io/docs/specification/components/
components:
    parameters:
        $ref: "./parameters/_index.yaml"
    schemas:
        $ref: "./schemas/_index.yaml"
    securitySchemes:
        $ref: "./securitySchemas/_index.yaml"

#https://swagger.io/docs/specification/authentication/api-keys/        
security:
    - ApiKey: []
    - PartnerKey: []

