openapi: "3.0.0"
info:
    version: "1.0.0"
    title: "POC for API Documentation"
    description:  "POC for API Doc Design and Collaboration"
servers:
    - url: https://localhost:9292
    - url: https://qa.goshd.com
tags:
  - name: Examples
  - name: Charts

paths:
    /api/meta/charts:
        $ref: "./paths/charts/charts.yaml"
    /api/meta/charts/{chartId}/edition:
        $ref: "./paths/charts/chart.yaml"
    /api/emaples:
        $ref: "./paths/examples/examples.yaml"
    /api/emaples/{exampleId}:
        $ref: "./paths/examples/example.yaml"
components:
    parameters:
        $ref: "./parameters/_index.yaml"
    schemas:
        $ref: "./schemas/_index.yaml"
    securitySchemes:
        $ref: "./securitySchemas/_index.yaml"

#https://swagger.io/docs/specification/authentication/api-keys/        
security:
    - ApiKey: []
    - PartnerKey: []

